name: Updater!
on:
  push:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  linux:
    name: Check for new Launcher versions
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Running updatemc.sh
      run: ./updatemc.sh
    - uses: EndBug/add-and-commit@v7.0.0
      with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'Updated resources!'
